import os
MONGO_DB_CLUSTER = 'MONGO_DB_CLUSTER'
MONGO_DB_USER = 'MONGO_DB_USER'
MONGO_DB_NAME = 'MONGO_DB_NAME_V2'
MONGO_DB_PASSWORD = 'MONGO_DB_PASSWORD'
MONGO_PREFIX = "mongodb+srv://"
MONGO_SUFFIX = ".mongodb.net"
CONNECTION_STRING = "mongodb+srv://" + MONGO_DB_USER + ":" + MONGO_DB_PASSWORD + "@" + MONGO_DB_CLUSTER + ".mongodb.net"
